const Flags = {
  "USD": require("../../assets/images/united-states.png"),
  "EUR": require("../../assets/images/european-union.png"),
  "SGD": require("../../assets/images/singapore.png"),
  "GBP": require("../../assets/images/united-kingdom.png"),
  "CHF": require("../../assets/images/switzerland.png"),
  "JPY": require("../../assets/images/japan.png"),
  "AUD": require("../../assets/images/australia.png"),
  "BDT": require("../../assets/images/bangladesh.png"),
  "BND": require("../../assets/images/brunei.png"),
  "KHR": require("../../assets/images/cambodia.png"),
  "CAD": require("../../assets/images/canada.png"),
  "CNY": require("../../assets/images/china.png"),
  "HKD": require("../../assets/images/hong-kong.png"),
  "INR": require("../../assets/images/india.png"),
  "IDR": require("../../assets/images/indonesia.png"),
  "KRW": require("../../assets/images/south-korea.png"),
  "LAK": require("../../assets/images/laos.png"),
  "MYR": require("../../assets/images/malaysia.png"),
  "NZD": require("../../assets/images/new-zealand.png"),
  "PKR": require("../../assets/images/pakistan.png"),
  "PHP": require("../../assets/images/philippines.png"),
  "LKR": require("../../assets/images/sri-lanka.png"),
  "THB": require("../../assets/images/thailand.png"),
  "VND": require("../../assets/images/vietnam.png"),
  "BRL": require("../../assets/images/brazil.png"),
  "CZK": require("../../assets/images/czech-republic.png"),
  "DKK": require("../../assets/images/denmark.png"),
  "EGP": require("../../assets/images/egypt.png"),
  "ILS": require("../../assets/images/israel.png"),
  "KES": require("../../assets/images/kenya.png"),
  "KWD": require("../../assets/images/kuwait.png"),
  "NPR": require("../../assets/images/nepal.png"),
  "NOK": require("../../assets/images/norway.png"),
  "RUB": require("../../assets/images/russia.png"),
  "SAR": require("../../assets/images/saudi-arabia.png"),
  "RSD": require("../../assets/images/serbia.png"),
  "ZAR": require("../../assets/images/south-africa.png"),
  "SEK": require("../../assets/images/serbia.png"),
};

export default Flags;
